### ISSUE TITLE
Doesn't recognize extra ' character in key

### ISSUE THREAD

**Issue by malodie** [AtomLinter/linter-js-yaml#117]
The lint does not recognize the additional ' character, particularly after an embedded ruby block.

The atom yaml language picks up the error and colors the malformation differently, but the linter shows with no errors.

Example of yaml that should be linted (includes extra ' in the key):
        `ip: <%= ENV['IP'] %>`
        `replica_id': '1'`
        `existing_replica_id': '1'`

Corrected yaml:
        `ip: <%= ENV['IP'] %>`
        `replica_id: '1'`
        `existing_replica_id: '1'`

This may be entirely because of erb (this is being used with Chef).

**Comment by malodie** [comment]
Another thought.  Is ' a valid character in a key?

**Comment by malodie** [comment]
After further research, technically, this is valid YAML, even though it is undesired.

**Comment by Arcanemagus** [comment]
FYI this package is just a wrapper around https://github.com/connec/yaml-js, so issues like that would need to be filed there. Since you say this is valid YAML though it sounds like this is more a bug in the "atom yaml language" ([language-yaml](https://github.com/atom/language-yaml)?) that it colors that wrong.
